// Interests options for use in forms (English only, no government or political topics)
const interests = [
  { value: "football", label: "Football" },
  { value: "handball", label: "Handball" },
  { value: "swimming", label: "Swimming" },
  { value: "reading", label: "Reading" },
  { value: "music", label: "Music" },
  { value: "singing", label: "Singing" },
  { value: "drawing", label: "Drawing" },
  { value: "calligraphy", label: "Calligraphy" },
  { value: "photography", label: "Photography" },
  { value: "travel", label: "Travel" },
  { value: "cooking", label: "Cooking" },
  { value: "cinema", label: "Cinema" },
  { value: "comedy", label: "Comedy" },
  { value: "technology", label: "Technology" },
  { value: "programming", label: "Programming" },
  { value: "gaming", label: "Gaming" },
  { value: "fitness", label: "Fitness" },
  { value: "gym", label: "Gym" },
  { value: "basketball", label: "Basketball" },
  { value: "volleyball", label: "Volleyball" },
  { value: "fishing", label: "Fishing" },
  { value: "desertTrips", label: "Desert Trips" },
  { value: "nileTrips", label: "Nile Trips" },
  { value: "handcrafts", label: "Handcrafts" },
  { value: "shopping", label: "Shopping" },
  { value: "fashion", label: "Fashion" },
  { value: "socialMedia", label: "Social Media" },
  { value: "dancing", label: "Dancing" },
  { value: "gardening", label: "Gardening" },
  { value: "pets", label: "Pets" },
  { value: "birds", label: "Birds" },
  { value: "cars", label: "Cars" },
  { value: "motorcycles", label: "Motorcycles" },
  { value: "streetFood", label: "Street Food" },
  { value: "tea", label: "Tea" },
  { value: "coffee", label: "Coffee" },
  { value: "boardGames", label: "Board Games" },
  { value: "domino", label: "Domino" },
  { value: "backgammon", label: "Backgammon" },
  { value: "chess", label: "Chess" },
  { value: "education", label: "Education" },
  { value: "science", label: "Science" },
  { value: "mathematics", label: "Mathematics" },
  { value: "languages", label: "Languages" },
  { value: "english", label: "English" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "arabic", label: "Arabic" },
  { value: "travelAbroad", label: "Travel Abroad" },
  { value: "business", label: "Business" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "marketing", label: "Marketing" },
  { value: "sales", label: "Sales" },
  { value: "finance", label: "Finance" },
  { value: "investment", label: "Investment" },
  { value: "medicine", label: "Medicine" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "dentistry", label: "Dentistry" },
  { value: "nursing", label: "Nursing" },
  { value: "engineering", label: "Engineering" },
  { value: "architecture", label: "Architecture" },
  { value: "agriculture", label: "Agriculture" },
  { value: "environment", label: "Environment" },
  { value: "climate", label: "Climate" },
  { value: "animals", label: "Animals" },
  { value: "birdWatching", label: "Bird Watching" },
  { value: "hiking", label: "Hiking" },
  { value: "cycling", label: "Cycling" },
  { value: "running", label: "Running" },
  { value: "camping", label: "Camping" },
  { value: "mountains", label: "Mountains" },
  { value: "sea", label: "Sea" }
];

export default interests;
